name: "🐛 Bug"
description: "버그 수정"
labels: ["Bug"]
title: "[BE/FE] "
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 내용
      description: 어떤 문제가 발생했나요?
      placeholder: 예) 장바구니 총액이 잘못 계산됨
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷 / 로그
    validations:
      required: false
