name: "🛠 Refactor"
description: "코드 품질 개선 및 리팩터링"
labels: ["Refactor"]
title: "[BE/FE] "
body:
  - type: dropdown
    id: refactor-type
    attributes:
      label: 리팩터링 유형
      options:
        - 🔄 코드 중복 제거
        - 🏗️ 구조 개선
        - 📝 네이밍 개선
        - ⚡ 성능 최적화
        - 🧪 테스트 코드 개선
        - 📦 의존성 정리
        - 🎨 코드 스타일 통일
        - 기타
    validations:
      required: true

  - type: textarea
    id: target
    attributes:
      label: 리팩터링 대상
      description: 어떤 코드/모듈/구조를 리팩터링하나요?
    validations:
      required: true

  - type: textarea
    id: current-problem
    attributes:
      label: 현재 문제점
      description: 지금 코드의 어떤 점이 문제인가요?
    validations:
      required: false
