spring:
  datasource:
    url: jdbc:h2:mem:motionit;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 0

logging:
  level:
    org.hibernate.SQL: warn