spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://motionit-db.cv860mq2wyus.ap-northeast-2.rds.amazonaws.com:3306/motionit?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: motionit123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 팀 공유용 update 사용. 실 서버에 반영됨

logging:
  level:
    org.hibernate.SQL: DEBUG
